export const PLATFORM_PORT = 3000;
export const NOVAMART_PORT = 3001;
export const NOVAMART_PROJECT_KEY = "novamart-bundled-demo";

export const PROJECT_TYPES = ["BUNDLED_DEMO", "EXTERNAL_AUDIT"] as const;
export const PROJECT_STATUSES = ["ACTIVE", "ARCHIVED", "ERROR"] as const;
export const SCAN_STATUSES = ["QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELLED"] as const;
export const SCAN_STAGES = ["QUEUED", "INITIALIZING", "EXPLORING", "AUDITING", "PROCESSING_RESULTS", "MAPPING", "REPAIRING", "AWAITING_APPROVAL", "EVALUATING", "COMPLETED"] as const;
export const ISSUE_IMPACTS = ["CRITICAL", "SERIOUS", "MODERATE", "MINOR", "UNKNOWN"] as const;
export const ISSUE_STATUSES = ["OPEN", "RESOLVED", "IGNORED", "REGRESSION"] as const;
export const REPAIR_STATUSES = ["GENERATING", "PROPOSED", "WAITING_FOR_APPROVAL", "APPROVED", "APPLYING", "APPLIED", "VERIFYING", "VERIFIED", "REJECTED", "FAILED", "ROLLED_BACK"] as const;
export const RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"] as const;
export const EVALUATION_STATUSES = ["QUEUED", "RUNNING_TESTS", "RESCANNING", "COMPARING", "PASSED", "PARTIAL", "FAILED"] as const;
export const AGENTS = ["SYSTEM", "EXPLORER", "AUDIT", "CONTEXT", "REPAIR", "EVALUATION", "HUMAN"] as const;
export const EVENT_STATUSES = ["INFO", "RUNNING", "SUCCEEDED", "FAILED", "WAITING"] as const;
